# Description.
model_template_id: MobileNet-V3-large-0.75x
name: MobileNet-V3-large-0.75x
task_type: CLASSIFICATION
task_family: VISION
instantiation: "CLASS"
summary: Custom Image Classification MobileNet-V3-large-0.75x
application:
  ~

# Algo backend.
framework: OTEClassification v1.2.3

# Task implementations.
entrypoints:
  base: torchreid.integration.sc.train_task.OTEClassificationTrainingTask
  openvino: torchreid.integration.sc.openvino_task.OpenVINOClassificationTask
  nncf: torchreid.integration.sc.nncf_task.OTEClassificationNNCFTask

# Capabilities.
capabilities:
  - compute_representations
  - compute_uncertainty_score

# Hyperparameters.
hyper_parameters:
  base_path: "../../../torchreid/integration/sc/configuration.yaml"
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 32
      max_num_epochs:
        default_value: 200
      learning_rate:
        default_value: 0.016
    nncf_optimization:
      enable_quantization:
        default_value: true
      enable_pruning:
        default_value: false
      maximal_accuracy_degradation:
        default_value: 1.0

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU

# Stats.
gigaflops: 0.32
size: 2.76
